import { Eye, EyeOff, Moon, ShieldCheck, Sun } from 'lucide-react'
import { FormEvent, ReactNode, useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ApiError } from '../api/client'
import { signIn } from '../auth'

export function Login() {
  const navigate = useNavigate(); const [theme, setTheme] = useTheme(); const [showPassword, setShowPassword] = useState(false); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false)
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setNotice(''); setLoading(true); const form = new FormData(event.currentTarget); try { await signIn(String(form.get('identity') ?? ''), String(form.get('password') ?? '')); navigate('/dashboard', { replace: true }) } catch (error) { setNotice(error instanceof ApiError ? error.message : 'Unable to sign in. Please try again.') } finally { setLoading(false) } }
  return <AuthShell theme={theme} setTheme={setTheme}><div className="login-panel-wrap"><form className="login-panel" onSubmit={handleSubmit}><div className="login-copy"><h2>Welcome back</h2><p>Sign in to your SAT-SA workspace</p></div><div className="login-fields"><label htmlFor="login-identity">Email or username</label><input id="login-identity" name="identity" type="text" autoComplete="username" placeholder="you@organization.com" required disabled={loading}/><label htmlFor="login-password">Password</label><PasswordInput id="login-password" name="password" show={showPassword} setShow={setShowPassword} autoComplete="current-password" disabled={loading}/></div>{notice && <p className="login-notice" role="alert">{notice}</p>}<button className="login-submit" type="submit" disabled={loading}>{loading ? 'Signing in…' : <>Sign in <span aria-hidden="true">→</span></>}</button><p className="login-switch">New to SAT-SA? <Link to="/signup">Create an account</Link></p><p className="login-footnote"><ShieldCheck size={14} aria-hidden="true"/> Secure workspace access</p></form></div></AuthShell>
}

export function useTheme() { const [theme, setTheme] = useState<'dark' | 'light'>(() => localStorage.getItem('sat-sa-theme') === 'light' ? 'light' : 'dark'); useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('sat-sa-theme', theme) }, [theme]); return [theme, setTheme] as const }
export function AuthShell({ theme, setTheme, children }: { theme: 'dark' | 'light'; setTheme: (theme: 'dark' | 'light') => void; children: ReactNode }) { return <main className="login-page"><div className="login-ambient login-ambient-cyan" aria-hidden="true"/><div className="login-ambient login-ambient-violet" aria-hidden="true"/><div className="login-grid" aria-hidden="true"/><header className="login-header"><Link className="login-brand" to="/login" aria-label="SAT-SA sign in"><span className="login-brand-mark"><ShieldCheck size={17} strokeWidth={2.25}/></span><span>SAT-SA</span></Link><button className="login-theme-toggle" type="button" aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`} onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? <Sun size={17}/> : <Moon size={17}/>}</button></header><section className="login-layout" aria-label="SAT-SA authentication"><div className="login-intro"><p className="login-eyebrow"><span/> Security intelligence platform</p><h1>Clarity for every<br/>security decision.</h1><p>Analyze, investigate, and respond with a unified view of operational risk.</p><div className="login-orbit" aria-hidden="true"><span className="orbit-node orbit-node-one"/><span className="orbit-node orbit-node-two"/><span className="orbit-node orbit-node-three"/><span className="orbit-core"><ShieldCheck size={20}/></span></div></div>{children}</section></main> }
export function PasswordInput({ id, name, show, setShow, autoComplete, disabled, minLength }: { id: string; name: string; show: boolean; setShow: (value: boolean) => void; autoComplete: string; disabled: boolean; minLength?: number }) { return <div className="login-password-field"><input id={id} name={name} type={show ? 'text' : 'password'} autoComplete={autoComplete} placeholder="Enter your password" required disabled={disabled} minLength={minLength}/><button type="button" className="password-toggle" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(!show)} disabled={disabled}>{show ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div> }
